<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Souradeeps-MacBook-Air.local" failures="1" tests="1" name="Test3" time="13.748" errors="0" timestamp="2025-07-20T21:58:28 IST">
  <testcase classname="testCases.TC002_loginTest" name="verifyLogin" time="0.044">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
at testCases.TC002_loginTest.verifyLogin(TC002_loginTest.java:41)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- verifyLogin -->
</testsuite> <!-- Test3 -->
